# Generated by Django 6.0.3 on 2026-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="ID"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=255, verbose_name="ID пользователя"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="E-mail получателя"),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Тема письма"),
                ),
                ("message", models.TextField(verbose_name="Текст письма")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
