# Generated by Django 6.0.3 on 2026-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AddField(
            model_name="mailing",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество попыток"
            ),
        ),
    ]
